export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_ERROR = 'ADD_BOOK_ERROR';
export const ADD_BOOK_LOADING = 'ADD_BOOK_LOADING';

export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';
export const DELETE_BOOK_LOADING = 'DELETE_BOOK_LOADING';

export const EDIT_BOOK = 'EDIT_BOOK';
export const EDIT_BOOK_ERROR = 'EDIT_BOOK_ERROR';
export const EDIT_BOOK_LOADING = 'EDIT_BOOK_LOADING';

export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export const FETCH_BOOKS_LOADING = 'FETCH_BOOKS_LOADING';
